server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Impede erro 404 ao atualizar rotas do React (SPA fallback)
        try_files $uri $uri/ /index.html;
    }
}
